package com.agentecon.firm.decisions;

import com.agentecon.production.PriceUnknownException;

public interface IFinancials {
	
	public double getCash();
	
	/**
	 * How much should be spent to achieve maximum profits, given the current price beliefs
	 * @throws PriceUnknownException 
	 */
	public double getIdealCogs() throws PriceUnknownException;
	
	/**
	 * How much was actually spent on input goods yesterday 
	 */
	public double getLatestCogs();
	
	/**
	 * Income generated yesterday's selling of the good produced with the inputs from two days ago
	 */
	public double getLatestRevenue();
	
	/**
	 * Income expected to be generated by selling the currently available output goods at the current price belief  
	 */
	public double getExpectedRevenue();
	
	/**
	 * The amount that needs to be spent on fixed costs before actual production starts at the current price estimate.
	 */
	public double getFixedCosts();

	public double getProfits();

}
